"""Per-file text for fix_claims_2026_09_19.py. Entries are (old, new); an old
value starting with "re:" is a regular expression. "*" applies to every file."""

QM = "masa sebenar disahkan secara bertulis"

EXACT: dict[str, list[tuple[str, str]]] = {}

EXACT["*"] = [
    # English generic
    ("re:>\\s*4-Hour Delivery\\s*<", ">Fast Delivery<"),
    ("re:>\\s*4小时送货\\s*<", ">快速送货<"),
    ("re:>\\s*4 மணி நேர டெலிவரி\\s*<", ">விரைவான டெலிவரி<"),
    ("re:>\\s*Free Installation\\s*<", ">Installation &amp; Demo<"),
    ("re:>\\s*免费安装\\s*<", ">安装与演示<"),
    ("re:>\\s*இலவச நிறுவல்\\s*<", ">நிறுவல் &amp; செய்முறை<"),
    ("We install and train at no extra charge.", "We install and show you how to use it. Any charge is stated on your written quotation."),
    ("我们帮您安装并教您使用，无额外费用。", "我们帮您安装并教您使用，如有费用将在书面报价中注明。"),
    ("re:கூடுதல் கட்டணம் இல்லாமல் நிறுவி பயிற்சி அளிக்கி[^<]*",
     "நாங்கள் நிறுவி பயன்படுத்தும் முறையை கற்றுத் தருவோம். கட்டணம் ஏதேனும் இருந்தால் எழுத்துப்பூர்வ விலைப்பட்டியலில் குறிப்பிடப்படும்."),
    ("<strong>FREE:</strong> Setup & installation", "<strong>Provided:</strong> Setup &amp; installation (per quotation)"),
    ("<strong>FREE:</strong> Usage training", "<strong>Provided:</strong> Usage training"),
    ("<strong>FREE:</strong> Service & repair", "<strong>Support:</strong> Service &amp; repair during rental (per terms)"),
    ("<strong>免费：</strong>安装与设置", "<strong>提供：</strong>安装与设置（按报价）"),
    ("<strong>免费：</strong>使用培训", "<strong>提供：</strong>使用培训"),
    ("<strong>免费：</strong>维修与保养", "<strong>支持：</strong>租赁期间维修与保养（按条款）"),
    ("<strong>இலவசம்:</strong> செட்அப் & நிறுவல்", "<strong>வழங்கப்படும்:</strong> செட்அப் &amp; நிறுவல் (விலைப்பட்டியலின்படி)"),
    ("<strong>இலவசம்:</strong> பயன்பாட்டு பயிற்சி", "<strong>வழங்கப்படும்:</strong> பயன்பாட்டு பயிற்சி"),
    ("<strong>இலவசம்:</strong> சேவை & பழுதுபார்ப்பு", "<strong>ஆதரவு:</strong> வாடகையின் போது சேவை &amp; பழுதுபார்ப்பு (விதிமுறைகளின்படி)"),
    ('alt="Free hospital bed installation"', 'alt="Hospital bed installation at home"'),
    ('alt="免费安装医院床"', 'alt="上门安装医院床"'),
    ('alt="இலவச மருத்துவமனை கட்டில் நிறுவல்"', 'alt="வீட்டில் மருத்துவமனை கட்டில் நிறுவல்"'),
    ("re:<small>分期：</small> <span>sebut harga bertulis<small>/月</small></span>", "<small>分期：</small> <span>以书面报价为准</span>"),
    ("re:<small>தவணை:</small> <span>sebut harga bertulis<small>/மாதம்</small></span>", "<small>தவணை:</small> <span>எழுத்துப்பூர்வ விலைப்பட்டியலின்படி</span>"),
]

# ------------------------------------------------------------------ ms home
EXACT["index.html"] = [
    ("Sewa Katil Hospital Malaysia | Penghantaran 4 Jam | Tanpa Deposit 2026",
     "Sewa Katil Hospital Malaysia | Dari RM150/Bulan | Tanpa Deposit 2026"),
    ("Sewa katil hospital dari RM150/bulan, beli dari RM799. Tanpa deposit, penghantaran 4 jam, servis percuma.",
     "Sewa katil hospital dari RM150/bulan, beli dari RM799. Tanpa deposit, bayar selepas katil dipasang. Penghantaran seawal 4 jam (disahkan bertulis)."),
    ("Penyedia perkhidmatan sewa dan jualan katil hospital terkemuka di Malaysia sejak 2016. Dipercayai oleh keluarga di seluruh Malaysia. Penghantaran 4 jam, tanpa deposit, servis percuma.",
     "Penyedia perkhidmatan sewa dan jualan katil hospital di Malaysia sejak 2016. Tanpa deposit, bayar selepas katil dipasang; penghantaran seawal 4 jam untuk tempahan terpilih (disahkan bertulis)."),
    ("Proses mudah, penghantaran same-day, tanpa deposit.", "Proses mudah, penghantaran pantas, tanpa deposit."),
    ("Pilih antara katil 2 fungsi (RM150/bulan), 3 fungsi (RM200-250/bulan), atau elektrik (RM300-350/bulan).",
     "Pilih antara katil 2 fungsi (RM150/bulan), 3 fungsi (RM250/bulan), atau 3 fungsi auto (RM450/bulan)."),
    ("Penghantaran dalam 4 jam untuk kawasan KL/Selangor, 24-48 jam untuk negeri lain.",
     f"Penghantaran seawal 4 jam untuk tempahan terpilih di KL/Selangor dan seawal 24 jam untuk negeri lain; {QM}."),
    ("Kami akan ambil semula katil secara percuma.", "Kami akan uruskan pengambilan semula katil; caj, jika ada, dinyatakan dalam sebut harga."),
    ("Adakah pemasangan katil hospital percuma?", "Adakah pemasangan katil hospital disediakan?"),
    ("re:Ya, pemasangan PERCUMA ke seluruh Malaysia termasuk[^\"]*",
     "Ya, pasukan kami memasang dan menunjukkan cara guna katil di seluruh Malaysia, termasuk Kuala Lumpur, Petaling Jaya, Shah Alam, Subang Jaya, Cheras dan Klang. Caj pemasangan dan penghantaran (penghantaran sehala dalam Malaysia sehingga RM280) dinyatakan dalam sebut harga bertulis mengikut alamat."),
    ("re:Untuk kawasan Lembah Klang, penghantaran dalam masa 4 jam dari pengesahan tempahan\\.[^\"]*",
     f"Untuk tempahan terpilih di Lembah Klang, penghantaran boleh seawal 4 jam dari pengesahan tempahan; di luar Lembah Klang, seawal 24 jam untuk Semenanjung dan 2-3 hari untuk Sabah/Sarawak — {QM}. Technician kami pasang katil dan ajar cara penggunaan; sebarang caj dinyatakan dalam sebut harga."),
    ("dan kami menyediakan servis percuma sepanjang tempoh sewa.", "dan servis semasa sewa mengikut terma sewa bertulis."),
    ("Ya! Kami menawarkan ansuran 0% sehingga 24 bulan untuk pembelian katil hospital. Contoh: Katil 2 fungsi RM799 = RM33/bulan x 24 bulan. Jaminan 1 tahun untuk semua pembelian.",
     "Ya! Pelan ansuran tersedia untuk pembelian katil hospital, dan ia ditandatangani selepas katil dihantar — bukan sebelum. Tempoh dan jumlah bulanan dinyatakan dalam sebut harga bertulis. Jaminan 1 tahun untuk katil baharu."),
    ("re:Jangan risau! Servis dan penyelenggaraan adalah PERCUMA sepanjang tempoh sewa\\.[^\"]*",
     "Jangan risau! Servis dan penyelenggaraan semasa sewa mengikut terma sewa bertulis. Jika ada masalah, hubungi kami dan kami akan atur technician untuk baiki atau tukar katil secepat mungkin."),
    ("dengan penghantaran 3 jam, tanpa deposit, dan sokongan 24/7.",
     "tanpa deposit, penghantaran seawal 3 jam untuk tempahan terpilih di Lembah Klang (disahkan bertulis), dan sokongan 24/7."),
    ("Penghantaran 4 jam. Servis & repair percuma.<br>", "Penghantaran seawal 4 jam (disahkan bertulis). Bayar selepas katil dipasang.<br>"),
    ("<p>Penghantaran pantas ke seluruh Malaysia. 4 jam KL-Selangor</p>",
     "<p>Penghantaran ke seluruh Malaysia. Seawal 4 jam untuk tempahan terpilih di KL-Selangor (disahkan bertulis)</p>"),
    ("Penghantaran Segera — Hari Ini Juga", "Penghantaran Segera — Semak Slot Hari Ini"),
    ("Order sebelum 2PM, katil sampai petang ni.", "Order sebelum 2PM dan kami semak slot penghantaran hari yang sama; slot hanya sah selepas disahkan secara bertulis."),
    ("Sewa tanpa deposit atau beli ansuran dengan 0% interest sehingga 12 bulan", "Sewa tanpa deposit, atau beli secara ansuran — ditandatangani selepas penghantaran"),
    ("Penghantaran Katil Hospital ke seluruh Malaysia. 3-4 jam KL Selangor",
     "Penghantaran Katil Hospital ke seluruh Malaysia. Seawal 3 jam untuk tempahan terpilih di KL Selangor (disahkan bertulis)"),
    ("4.9/5 bintang dari 500+ ulasan Google - bukan kami yang cakap, pelanggan yang buktikan",
     "Ulasan sebenar pelanggan di Google - bukan kami yang cakap, pelanggan yang buktikan"),
    ("<strong>Pemasangan PERCUMA</strong> - Pasukan kami akan datang pasang katil di rumah anda tanpa sebarang caj tambahan.",
     "<strong>Pemasangan</strong> - Pasukan kami akan datang pasang katil di rumah anda; sebarang caj dinyatakan dalam sebut harga bertulis."),
    ("re:>\\s*500\\+ ulasan\\s*<", ">Ulasan Google<"),
]

# ------------------------------------------------------------------ en home
EXACT["en/index.html"] = [
    ("Hospital Bed Rental Malaysia | 4-Hour Delivery | No Deposit 2026", "Hospital Bed Rental Malaysia | From RM150/Month | No Deposit 2026"),
    ("Rent hospital bed from RM150/month, buy from RM799. No deposit, 4-hour delivery, free service. Trusted by 500+ Malaysian families.",
     "Rent a hospital bed from RM150/month, buy from RM799. No deposit, pay after the bed is installed. Delivery from 4 hours for selected orders (confirmed in writing)."),
    ("Leading hospital bed rental and sales provider in Malaysia since 2016. Trusted by 500+ families. 4-hour delivery, no deposit, free service.",
     "Hospital bed rental and sales provider in Malaysia since 2016. No deposit, pay after installation; delivery from 4 hours for selected orders, confirmed in writing."),
    ("Easy process, same-day delivery, no deposit.", "Easy process, fast delivery, no deposit."),
    ("Choose between 2 function bed (RM150/month), 3 function (RM200-250/month), or electric (RM300-350/month).",
     "Choose between a 2 function bed (RM150/month), 3 function (RM250/month) or 3 function auto (RM450/month)."),
    ("Delivery within 4 hours for KL/Selangor area, 24-48 hours for other states.",
     "Delivery from 4 hours for selected KL/Selangor orders and from 24 hours for other states; the actual time is confirmed in writing."),
    ("We will collect the bed for free.", "We arrange collection of the bed; any charge is stated on your quotation."),
    ("Is hospital bed setup free?", "Do you set up the hospital bed?"),
    ("re:Yes, FREE professional setup and installation throughout Malaysia[^\"]*",
     "Yes. Our team installs the bed and shows you how to use it throughout Malaysia, including Kuala Lumpur, Petaling Jaya, Shah Alam, Subang Jaya, Cheras and Klang. Any setup and delivery charges (one-way delivery within Malaysia is up to RM280) are stated on your written quotation."),
    ("re:For the Klang Valley area, delivery within 4 hours from booking confirmation\\.[^\"]*",
     "For selected Klang Valley orders, delivery can be as fast as 4 hours from booking confirmation; outside the Klang Valley, from 24 hours for Peninsular Malaysia and 2-3 days for Sabah/Sarawak — the actual time is confirmed in writing. Our technician installs the bed and teaches you how to use it; any charge is on your quotation."),
    ("re:and we provide free service throughout the rental period\\.", "and service during the rental follows your written rental terms."),
    ("Yes! We offer 0% instalment up to 24 months for hospital bed purchases. Example: 2 function bed RM799 = RM33/month x 24 months. 1-year warranty for all purchases.",
     "Yes! Instalment plans are available for hospital bed purchases and are signed after the bed is delivered, not before. The term and monthly amount are set out on your written quotation. New hospital beds carry a 1-year warranty."),
    ("re:Don't worry! Service and maintenance are FREE throughout the rental period\\.[^\"]*",
     "Don't worry! Service and maintenance during the rental follow your written rental terms. If there's any issue, contact us and we will arrange a technician to repair or replace the bed as quickly as possible."),
    ("Hospital bed rental and sales service for home use. 4-hour delivery, no deposit, free service.",
     "Hospital bed rental and sales service for home use. No deposit, pay after installation; delivery from 4 hours for selected orders (confirmed in writing)."),
    ("with 3-hour delivery, no deposit, and 24/7 support.", "with no deposit, delivery from 3 hours for selected Klang Valley orders (confirmed in writing), and 24/7 support."),
    ("4-hour delivery. Free service & repair.<br>", "Delivery from 4 hours for selected orders (confirmed in writing). Pay after installation.<br>"),
    ("Trusted by 500+ Malaysian families.", "Serving Malaysian families since 2016."),
    ("<p>Fast delivery throughout Malaysia. 4 hours KL-Selangor</p>", "<p>Delivery throughout Malaysia. From 4 hours for selected KL-Selangor orders (confirmed in writing)</p>"),
    ("Why 500+ Malaysian Families Choose Us?", "Why Malaysian Families Choose Us"),
    ("Rent with no deposit or buy on instalment with 0% interest up to 12 months", "Rent with no deposit, or buy on instalment — signed after delivery"),
    ("Hospital bed delivery throughout Malaysia. 3-4 hours KL Selangor", "Hospital bed delivery throughout Malaysia. From 3 hours for selected KL Selangor orders (confirmed in writing)"),
    ("Free Installation & Training", "Installation &amp; Training"),
    ("Free demonstration and training on hospital bed usage for users and caregivers", "Demonstration and training on hospital bed usage for users and caregivers during installation"),
    ("4.9/5 stars from 500+ Google reviews - we don't say it, our customers prove it", "Real customer reviews on Google - we don't say it, our customers prove it"),
    ("<strong>FREE Installation</strong> - Our team will come and install the bed at your home at no extra charge.",
     "<strong>Installation</strong> - Our team will come and install the bed at your home; any charge is stated on your written quotation."),
    ("We Deliver Today.", "Check Today's Delivery Slots."),
    ("Contact us now for delivery <strong>within 2-4 hours</strong> to your home.",
     "Contact us now for delivery <strong>from 3 hours</strong> to your home (time confirmed in writing)."),
    ("re:>\\s*500\\+ reviews\\s*<", ">Google reviews<"),
]

# ------------------------------------------------------------------ zh home
EXACT["zh/index.html"] = [
    ("医院床出租马来西亚 | 4小时送货 | 无需押金 2026", "医院床出租马来西亚 | 每月RM150起 | 无需押金 2026"),
    ("医院床出租从RM150/月起，购买从RM799起。无需押金，4小时送货，免费维修服务。500+马来西亚家庭信赖之选。",
     "医院床出租从RM150/月起，购买从RM799起。无需押金，床送达安装后才付款。部分订单最快4小时送达（以书面确认为准）。"),
    ("马来西亚领先的医院床租赁与销售服务商，自2016年起。500+家庭信赖之选。4小时送货，无需押金，免费维修。",
     "马来西亚医院床租赁与销售服务商，自2016年起。无需押金，安装后付款；部分订单最快4小时送达（以书面确认为准）。"),
    ("流程简单，当天送货，无需押金。", "流程简单，快速送货，无需押金。"),
    ("选择2功能床（RM150/月）、3功能床（RM200-250/月）或电动床（RM300-350/月）。", "选择2功能床（RM150/月）、3功能床（RM250/月）或3功能自动床（RM450/月）。"),
    ("吉隆坡/雪兰莪地区4小时送达，其他州24-48小时。", "吉隆坡/雪兰莪部分订单最快4小时送达，其他州最快24小时；实际时间以书面确认为准。"),
    ("我们将免费取回床。", "我们会安排取回床；如有费用，将在报价中注明。"),
    ("医院床送货免费吗？", "医院床送货收费吗？"),
    ("re:是的，巴生谷地区免费送货[^\"]*", "送货费用按地址而定：马来西亚境内单程送货最高RM280，实际费用以书面报价为准。巴生谷部分订单最快4小时送达（以书面确认为准）。"),
    ("re:巴生谷地区，确认预订后4小时内送达。[^\"]*",
     "巴生谷部分订单确认后最快4小时送达；巴生谷以外，半岛马来西亚最快24小时，沙巴/砂拉越2-3天（实际时间以书面确认为准）。我们的技术人员负责安装并教您使用方法，如有费用将在报价中注明。"),
    ("我们在整个租赁期间提供免费维修服务。", "租赁期间的维修服务按书面租赁条款执行。"),
    ("可以！我们提供长达24个月的0%分期付款购买医院床。例如：2功能床RM799 = RM33/月 x 24个月。所有购买享1年保修。",
     "可以！购买医院床可选择分期付款，分期协议在床送达后才签署。期数和月供以书面报价为准。新床享1年保修。"),
    ("re:别担心！整个租赁期间维修和保养完全免费。[^\"]*", "别担心！租赁期间的维修和保养按书面租赁条款执行。如有问题，请联系我们，我们会尽快安排技术人员上门维修或更换床。"),
    ("家用医院床租赁与销售服务。4小时送货，无需押金，免费维修。", "家用医院床租赁与销售服务。无需押金，安装后付款；部分订单最快4小时送达（以书面确认为准）。"),
    ("马来西亚全国医院床租赁服务，3小时送货，无需押金，24/7支持。", "马来西亚全国医院床租赁服务，无需押金，巴生谷部分订单最快3小时送达（以书面确认为准），24/7支持。"),
    ("4小时送货。免费维修服务。<br>", "部分订单最快4小时送达（以书面确认为准）。安装后付款。<br>"),
    ("500+马来西亚家庭信赖之选。", "自2016年起服务马来西亚家庭。"),
    ("<p>全马来西亚快速送货。吉隆坡-雪兰莪4小时</p>", "<p>全马来西亚送货。吉隆坡-雪兰莪部分订单最快4小时（以书面确认为准）</p>"),
    ("为什么500+马来西亚家庭选择我们？", "为什么马来西亚家庭选择我们？"),
    ("无押金租赁或0%利息分期购买，最长12个月", "无押金租赁，或分期购买——分期协议在送达后签署"),
    ("医院床送货至全马来西亚。吉隆坡雪兰莪3-4小时", "医院床送货至全马来西亚。吉隆坡雪兰莪部分订单最快3小时（以书面确认为准）"),
    ("免费安装与培训", "安装与培训"),
    ("免费为用户和护理者演示和培训医院床使用方法", "安装时为用户和护理者演示和培训医院床使用方法"),
    ('值得信赖的卖家，获<span style="color: #1e4a9e;">马来西亚MDA</span>认证', '值得信赖的卖家，已在<span style="color: #1e4a9e;">马来西亚MDA</span>注册'),
    ("4.9/5星，来自500+谷歌评论——不是我们说的，是客户证明的", "真实客户谷歌评论——不是我们说的，是客户证明的"),
    ("<strong>免费安装</strong> - 我们的团队将到您家安装床，无任何额外费用。", "<strong>安装</strong> - 我们的团队将到您家安装床，如有费用将在书面报价中注明。"),
    ("我们今天就送到。", "查询今天的送货时段。"),
    ("立即联系我们，<strong>2-4小时内</strong>送货上门。", "立即联系我们，<strong>最快3小时</strong>送货上门（以书面确认为准）。"),
    ("re:>\\s*500\\+评论\\s*<", ">谷歌评论<"),
]

# ------------------------------------------------------------------ ta home
TQ = "எழுத்துப்பூர்வ உறுதிப்படுத்தலுடன்"
EXACT["ta/index.html"] = [
    ("மருத்துவமனை கட்டில் வாடகை மலேசியா | 4 மணி நேர டெலிவரி 2026", "மருத்துவமனை கட்டில் வாடகை மலேசியா | RM150/மாதம் முதல் 2026"),
    ("டெபாசிட் இல்லை, 4 மணி நேர டெலிவரி, இலவச சேவை. 500+ மலேசிய குடும்பங்கள் நம்பிக்கை.",
     f"டெபாசிட் இல்லை, கட்டில் நிறுவிய பின் பணம் செலுத்துங்கள். தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே டெலிவரி ({TQ})."),
    ("500+ குடும்பங்கள் நம்பிக்கை. 4 மணி நேர டெலிவரி, டெபாசிட் இல்லை, இலவச சேவை.",
     f"டெபாசிட் இல்லை, நிறுவிய பின் பணம்; தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே டெலிவரி ({TQ})."),
    ("எளிய செயல்முறை, அதே நாள் டெலிவரி, டெபாசிட் இல்லை.", "எளிய செயல்முறை, விரைவான டெலிவரி, டெபாசிட் இல்லை."),
    ("3 செயல்பாடு (RM200-250/மாதம்), அல்லது மின்சார (RM300-350/மாதம்) கட்டிலைத்", "3 செயல்பாடு (RM250/மாதம்), அல்லது 3 செயல்பாடு ஆட்டோ (RM450/மாதம்) கட்டிலைத்"),
    ("KL/செலாங்கூர் பகுதிக்கு 4 மணி நேரத்தில், மற்ற மாநிலங்களுக்கு 24-48 மணி நேரம்.",
     "தேர்ந்தெடுக்கப்பட்ட KL/செலாங்கூர் ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே, மற்ற மாநிலங்களுக்கு 24 மணி நேரத்திலேயே; உண்மையான நேரம் எழுத்துப்பூர்வமாக உறுதிப்படுத்தப்படும்."),
    ("நாங்கள் இலவசமாக கட்டிலை எடுத்துச் செல்வோம்.", "கட்டிலை திரும்பப் பெற ஏற்பாடு செய்வோம்; கட்டணம் ஏதேனும் இருந்தால் விலைப்பட்டியலில் குறிப்பிடப்படும்."),
    ("மருத்துவமனை கட்டில் டெலிவரி இலவசமா?", "மருத்துவமனை கட்டில் டெலிவரிக்கு கட்டணம் உண்டா?"),
    ("re:ஆம், கோலாலம்பூர், பெட்டாலிங் ஜெயா, ஷா ஆலம்[^\"]*இலவச டெலிவரி[^\"]*",
     f"டெலிவரி கட்டணம் முகவரியைப் பொறுத்தது: மலேசியாவுக்குள் ஒரு வழி டெலிவரி அதிகபட்சம் RM280, உண்மையான கட்டணம் எழுத்துப்பூர்வ விலைப்பட்டியலில் குறிப்பிடப்படும். கிளாங் பள்ளத்தாக்கில் தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே டெலிவரி ({TQ})."),
    ("re:கிளாங் பள்ளத்தாக்கு பகுதிக்கு, புக்கிங் உறுதிசெய்தபின் 4 மணி நேரத்தில் டெலிவரி\\.[^\"]*",
     "கிளாங் பள்ளத்தாக்கில் தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு, புக்கிங் உறுதிசெய்தபின் 4 மணி நேரத்திலேயே டெலிவரி; வெளியே, தீபகற்ப மலேசியாவுக்கு 24 மணி நேரத்திலேயே, சபா/சரவாக்கிற்கு 2-3 நாட்கள் (உண்மையான நேரம் எழுத்துப்பூர்வமாக உறுதிப்படுத்தப்படும்). எங்கள் தொழில்நுட்பர் கட்டிலை நிறுவி பயன்படுத்தும் முறையை கற்றுத் தருவார்; கட்டணம் ஏதேனும் இருந்தால் விலைப்பட்டியலில் குறிப்பிடப்படும்."),
    ("இணங்குகின்றன, வாடகை காலம் முழுவதும் இலவச சேவை.", "இணங்குகின்றன; வாடகையின் போது சேவை எழுத்துப்பூர்வ வாடகை விதிமுறைகளின்படி."),
    ("ஆம்! மருத்துவமனை கட்டில் வாங்குவதற்கு 24 மாதம் வரை 0% தவணை வழங்குகிறோம். உதாரணம்: 2 செயல்பாடு கட்டில் RM799 = RM33/மாதம் x 24 மாதம். அனைத்து கொள்முதல்களுக்கும் 2 ஆண்டு உத்தரவாதம்.",
     "ஆம்! மருத்துவமனை கட்டில் வாங்க தவணைத் திட்டம் உள்ளது; கட்டில் டெலிவரி செய்யப்பட்ட பிறகே அது கையெழுத்திடப்படும். காலம் மற்றும் மாதத் தொகை எழுத்துப்பூர்வ விலைப்பட்டியலில் குறிப்பிடப்படும். புதிய கட்டில்களுக்கு 1 ஆண்டு உத்தரவாதம்."),
    ("re:கவலைப்பட வேண்டாம்! வாடகை காலம் முழுவதும் சேவை மற்றும் பராமரிப்பு இலவசம்\\.[^\"]*",
     "கவலைப்பட வேண்டாம்! வாடகையின் போது சேவை மற்றும் பராமரிப்பு எழுத்துப்பூர்வ வாடகை விதிமுறைகளின்படி. ஏதாவது சிக்கல் இருந்தால், எங்களை தொடர்புகொள்ளுங்கள்; கட்டிலை சரிசெய்ய அல்லது மாற்ற தொழில்நுட்பரை விரைவில் ஏற்பாடு செய்வோம்."),
    ("வீட்டில் பயன்படுத்த மருத்துவமனை கட்டில் வாடகை மற்றும் விற்பனை சேவை. 4 மணி நேர டெலிவரி, டெபாசிட் இல்லை, இலவச சேவை.",
     f"வீட்டில் பயன்படுத்த மருத்துவமனை கட்டில் வாடகை மற்றும் விற்பனை சேவை. டெபாசிட் இல்லை, நிறுவிய பின் பணம்; தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே டெலிவரி ({TQ})."),
    ("3 மணி நேர டெலிவரி, டெபாசிட் இல்லை, 24/7 ஆதரவுடன் மலேசியா முழுவதும் மருத்துவமனை கட்டில் வாடகை சேவை.",
     f"டெபாசிட் இல்லை, கிளாங் பள்ளத்தாக்கில் தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 3 மணி நேரத்திலேயே டெலிவரி ({TQ}), 24/7 ஆதரவுடன் மலேசியா முழுவதும் மருத்துவமனை கட்டில் வாடகை சேவை."),
    ("4 மணி நேர டெலிவரி. இலவச சேவை & பழுதுபார்ப்பு.<br>", f"தேர்ந்தெடுக்கப்பட்ட ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே டெலிவரி ({TQ}). நிறுவிய பின் பணம்.<br>"),
    ("500+ மலேசிய குடும்பங்கள் எங்களை நம்புகின்றனர்.", "2016 முதல் மலேசிய குடும்பங்களுக்கு சேவை செய்கிறோம்."),
    ("<p>மலேசியா முழுவதும் விரைவான டெலிவரி. KL-செலாங்கூர் 4 மணி நேரம்</p>",
     f"<p>மலேசியா முழுவதும் டெலிவரி. தேர்ந்தெடுக்கப்பட்ட KL-செலாங்கூர் ஆர்டர்களுக்கு 4 மணி நேரத்திலேயே ({TQ})</p>"),
    ("ஏன் 500+ மலேசிய குடும்பங்கள் எங்களை தேர்வு செய்கின்றனர்?", "மலேசிய குடும்பங்கள் ஏன் எங்களை தேர்வு செய்கின்றனர்?"),
    ("டெபாசிட் இல்லாமல் வாடகை அல்லது 12 மாதம் வரை 0% வட்டி தவணையில் வாங்கவும்", "டெபாசிட் இல்லாமல் வாடகை, அல்லது தவணையில் வாங்கவும் — டெலிவரிக்குப் பின் கையெழுத்து"),
    ("மலேசியா முழுவதும் மருத்துவமனை கட்டில் டெலிவரி. KL செலாங்கூர் 3-4 மணி நேரம்",
     f"மலேசியா முழுவதும் மருத்துவமனை கட்டில் டெலிவரி. தேர்ந்தெடுக்கப்பட்ட KL செலாங்கூர் ஆர்டர்களுக்கு 3 மணி நேரத்திலேயே ({TQ})"),
    ("இலவச நிறுவல் மற்றும் பயிற்சி", "நிறுவல் மற்றும் பயிற்சி"),
    ("பயனர்கள் மற்றும் பராமரிப்பாளர்களுக்கு மருத்துவமனை கட்டில் பயன்பாட்டின் இலவச செய்முறை விளக்கம் மற்றும் பயிற்சி",
     "நிறுவலின் போது பயனர்கள் மற்றும் பராமரிப்பாளர்களுக்கு மருத்துவமனை கட்டில் பயன்பாட்டின் செய்முறை விளக்கம் மற்றும் பயிற்சி"),
    ('நம்பகமான விற்பனையாளர், <span style="color: #1e4a9e;">MDA மலேசியா</span> அங்கீகரிக்கப்பட்டது',
     'நம்பகமான விற்பனையாளர், <span style="color: #1e4a9e;">MDA மலேசியா</span>வில் பதிவு செய்யப்பட்டது'),
    ("500+ Google மதிப்புரைகளில் 4.9/5 நட்சத்திரங்கள் - நாங்கள் சொல்லவில்லை, வாடிக்கையாளர்கள் நிரூபிக்கிறார்கள்",
     "Google-இல் உண்மையான வாடிக்கையாளர் மதிப்புரைகள் - நாங்கள் சொல்லவில்லை, வாடிக்கையாளர்கள் நிரூபிக்கிறார்கள்"),
    ("<strong>இலவச நிறுவல்</strong> - எந்த கூடுதல் கட்டணமும் இல்லாமல் எங்கள் குழு உங்கள் வீட்டில் கட்டிலை நிறுவ வரும்.",
     "<strong>நிறுவல்</strong> - எங்கள் குழு உங்கள் வீட்டில் கட்டிலை நிறுவ வரும்; கட்டணம் ஏதேனும் இருந்தால் எழுத்துப்பூர்வ விலைப்பட்டியலில் குறிப்பிடப்படும்."),
    ("இன்றே டெலிவரி செய்கிறோம்.", "இன்றைய டெலிவரி நேரத்தை சரிபாருங்கள்."),
    ("உங்கள் வீட்டிற்கு <strong>2-4 மணி நேரத்தில்</strong> டெலிவரிக்கு இப்போது எங்களை தொடர்புகொள்ளுங்கள்.",
     f"உங்கள் வீட்டிற்கு <strong>3 மணி நேரத்திலேயே</strong> டெலிவரிக்கு ({TQ}) இப்போது எங்களை தொடர்புகொள்ளுங்கள்."),
    ("re:>\\s*500\\+ மதிப்புரைகள்\\s*<", ">Google மதிப்புரைகள்<"),
    ("2016 முதல் மலேசியா முழுவதும் 5,000+ திருப்தியான வாடிக்கையாளர்களுடன் நம்பகமானது", "2016 முதல் மலேசியா முழுவதும் குடும்பங்களுக்கு சேவை செய்கிறோம்"),
]

# ------------------------------------------------------ pages with own prose
Q3 = "seawal 3 jam untuk tempahan terpilih (masa sebenar disahkan secara bertulis)"
EXACT["katil-hospital-kuala-lumpur.html"] = [
    ("Sewa Katil Hospital KL | Penghantaran 2 Jam", "Sewa Katil Hospital KL | Tanpa Deposit, Hantar Pantas"),
    ("Hantar 2 jam ke Cheras, Bangsar, Kepong & Setapak.", "Hantar seawal 3 jam ke Cheras, Bangsar, Kepong & Setapak (disahkan bertulis)."),
    ("Betul ke penghantaran katil hospital ke KL boleh dalam 2 jam?", "Berapa cepat penghantaran katil hospital ke KL?"),
    (r"re:Ya, gudang kami di Batu Caves hanya (?:<strong>)?15 minit dari pusat KL(?:</strong>)?\. Untuk kawasan seperti Kepong, Setapak dan Sentul, penghantaran boleh secepat 20-30 minit\. Kawasan lain seperti Cheras, Bangsar dan Sri Petaling biasanya dalam masa 2 jam\. Order sebelum 2pm untuk penghantaran hari yang sama\.",
     "Gudang kami di Batu Caves dekat dengan pusat KL, jadi penghantaran ke Kepong, Setapak, Sentul, Cheras, Bangsar dan Sri Petaling boleh seawal 3 jam untuk tempahan terpilih — masa sebenar disahkan secara bertulis. Order sebelum 2pm dan kami semak slot penghantaran hari yang sama untuk anda."),
    ("Penghantaran express 2 jam ke seluruh KL dari gudang Batu Caves.", f"Penghantaran pantas ke seluruh KL dari gudang Batu Caves — {Q3}."),
    ("Gudang kami di Batu Caves hanya 15 minit dari pusat KL, membolehkan penghantaran express ke Cheras, Kepong, Bangsar, Setapak, Wangsa Maju, Mont Kiara dan seluruh KL dalam masa 2 jam.",
     f"Gudang kami di Batu Caves yang berdekatan dengan pusat KL membolehkan penghantaran pantas ke Cheras, Kepong, Bangsar, Setapak, Wangsa Maju, Mont Kiara dan seluruh KL, {Q3}."),
    ("katil boleh sampai secepat 2 jam.", "katil boleh sampai seawal 3 jam (masa sebenar disahkan secara bertulis)."),
    ("Katil Hospital Sampai Dalam 2 Jam.", "Semak Slot Penghantaran Hari Ini."),
    (r"re:Penghantaran: [0-9]+ minit dari gudang", "Penghantaran: seawal 3 jam (disahkan bertulis)"),
    ("Order sebelum 2pm untuk penghantaran hari yang sama.", "Order sebelum 2pm dan kami semak slot penghantaran hari yang sama (disahkan secara bertulis)."),
]
EXACT["katil-hospital-putrajaya.html"] = [
    ("Order sebelum 2pm untuk penghantaran hari yang sama.", "Order sebelum 2pm dan kami semak slot penghantaran hari yang sama (disahkan secara bertulis)."),
    (r"re:>\s*Hantar Hari Ini\s*<", ">Semak Slot Hari Ini<"),
]
EXACT["katil-hospital-selangor.html"] = [
    ("Kenapa penghantaran ke Selangor boleh secepat 4 jam?", "Kenapa penghantaran ke Selangor boleh pantas?"),
    (r"re:>\s*Hantar 4 Jam\s*<", ">Hantar Pantas<"),
]
EXACT["katil-hospital-labuan.html"] = [
    ("penghantaran ke mana-mana lokasi di pulau boleh diselesaikan dalam masa kurang dari sejam",
     "penghantaran ke mana-mana lokasi di pulau biasanya dapat diselesaikan dengan cepat"),
]
EXACT["tentang-kami.html"] = [
    ('Penghantaran 4 jam bermaksud 4 jam - bukan "dalam perjalanan".',
     'Masa penghantaran yang kami sahkan secara bertulis ialah masa yang kami tepati - bukan "dalam perjalanan".'),
    ("Untuk Lembah Klang. Kawasan lain dalam 24 jam.",
     "Seawal 4 jam untuk tempahan terpilih di Lembah Klang; kawasan lain seawal 24 jam — masa sebenar disahkan secara bertulis."),
    (r"re:(<strong[^>]*>)Penghantaran 4 Jam(</strong>)", r"\1Penghantaran Pantas\2"),
    ("re:✓ Penghantaran 4 Jam Untuk Lembah Klang", "✓ Penghantaran Pantas Lembah Klang (masa disahkan bertulis)"),
]
EXACT["contact.html"] = [
    ("Hubungi Kami | Respons 5 Minit, Penghantaran 4 Jam", "Hubungi Kami | Respons 5 Minit, Tanpa Deposit"),
    ("Penghantaran 4 jam ke Lembah Klang.", "Penghantaran seawal 4 jam ke Lembah Klang untuk tempahan terpilih (disahkan bertulis)."),
    ('<h3>Lembah Klang <span class="badge">Percuma</span></h3>', "<h3>Lembah Klang</h3>"),
]

EXACT["katil-hospital-selangor.html"] += [
    ("Shah Alam dalam 30 minit, PJ dalam 25 minit, Klang dalam 40 minit dan Kajang dalam 45 minit",
     "Shah Alam, PJ, Klang dan Kajang dengan pantas — penghantaran seawal 3 jam untuk tempahan terpilih, masa sebenar disahkan secara bertulis"),
    ("Shah Alam dalam 30 minit, Petaling Jaya dalam 25 minit, Klang dalam 40 minit, dan Kajang dalam 45 minit. Ini bermakna kebanyakan order yang disahkan sebelum 2pm akan sampai pada hari yang sama.",
     "Shah Alam, Petaling Jaya, Klang dan Kajang dengan pantas. Untuk order yang disahkan sebelum 2pm, kami semak slot penghantaran hari yang sama — masa sebenar disahkan secara bertulis."),
]
EXACT["katil-hospital-melaka.html"] = [
    ("dalam masa kurang dari sejam dari pusat penghantaran", "dengan mudah dari pusat penghantaran"),
]
EXACT["katil-hospital-shah-alam.html"] = [
    ("proses 15 minit, penghantaran 4 jam ke rumah anda.", "proses 15 minit, penghantaran seawal 4 jam ke rumah anda (disahkan bertulis)."),
]
EXACT["tentang-kami.html"] += [
    (r're:<span class="stat-number">500\+</span>(\s*)<span class="stat-label">Keluarga Dilayan</span>',
     r'<span class="stat-number">2016</span>\1<span class="stat-label">Tahun Ditubuhkan</span>'),
    (r're:<span class="stat-number">4\.9</span>(\s*)<span class="stat-label">Rating Purata</span>',
     r'<span class="stat-number">RM0</span>\1<span class="stat-label">Deposit Sewa</span>'),
]
EXACT["products/katil-hospital-2-fungsi.html"] = [
    ("Pilihan paling popular - 80% pelanggan pilih model ini.", "Pilihan paling popular dalam kalangan pelanggan kami."),
]
EXACT["ta/index.html"] += [
    ("(80% வாடிக்கையாளர்கள் இதைத் தேர்வு செய்கிறார்கள்)", "(பெரும்பாலான வாடிக்கையாளர்களின் தேர்வு)"),
]
EXACT["terms-conditions.html"] = [
    ("<h3>2.5 Pemasangan Percuma</h3>", "<h3>2.5 Pemasangan</h3>"),
    ("Setiap sewaan katil hospital termasuk perkhidmatan pemasangan dan pemasangan percuma. Pasukan kami akan:",
     "Pemasangan disediakan untuk setiap sewaan katil hospital; sebarang caj dinyatakan dalam sebut harga bertulis. Pasukan kami akan:"),
    ("<h3>3.3 Ansuran 0% Faedah</h3>", "<h3>3.3 Ansuran</h3>"),
    ("Syarikat menawarkan kemudahan pembayaran ansuran 0% faedah bagi pembelian katil hospital.",
     "Syarikat menawarkan kemudahan pembayaran ansuran bagi pembelian katil hospital; pelan ansuran ditandatangani selepas katil dihantar."),
    ("<h3>4.2 Pemasangan Percuma</h3>", "<h3>4.2 Pemasangan</h3>"),
    ("<strong>Pemasangan percuma</strong> disediakan untuk semua penghantaran katil hospital, sama ada sewaan atau pembelian.",
     "<strong>Pemasangan</strong> disediakan untuk penghantaran katil hospital, sama ada sewaan atau pembelian; sebarang caj dinyatakan dalam sebut harga bertulis."),
]
EXACT["rental/index.html"] = [
    ("Pemasangan PERCUMA. Pulangkan bila-bila masa.", "Bayar selepas katil dipasang. Pulangkan bila-bila masa."),
    ("WhatsApp sekarang untuk tempahan. Pemasangan <strong>PERCUMA</strong> di rumah anda.", "WhatsApp sekarang untuk tempahan. Bayar selepas katil dipasang di rumah anda."),
    ("✓ Pemasangan PERCUMA", "✓ Bayar Selepas Dipasang"),
    ("Kami tanggung — ganti atau baiki percuma", "Kami tanggung — ganti atau baiki ikut terma sewa"),
    ("Kami ganti / baiki percuma", "Kami ganti / baiki ikut terma sewa"),
]

# ------------------------------------------------------------------ purchase
EXACT["purchase/index.html"] = [
    ("Beli Katil Hospital | Jaminan 1 Tahun, Ansuran 0%", "Beli Katil Hospital | Dari RM799, Jaminan 1 Tahun"),
    ("Beli katil hospital dari RM1,300. Jaminan 1 tahun, ansuran 0% sehingga 24 bulan. Penghantaran 4 jam ke seluruh Malaysia.",
     "Beli katil hospital dari RM799. Jaminan 1 tahun untuk katil baharu, pelan ansuran ditandatangani selepas penghantaran. Penghantaran ke seluruh Malaysia; seawal 4 jam untuk tempahan terpilih di Lembah Klang (disahkan bertulis)."),
    ("Perkhidmatan jualan katil hospital di Malaysia. Jaminan 1 tahun, ansuran 0% sehingga 24 bulan. Penghantaran 4 jam ke seluruh Malaysia. Bermula dari RM1,300.",
     "Perkhidmatan jualan katil hospital di Malaysia. Jaminan 1 tahun untuk katil baharu, pelan ansuran tersedia. Penghantaran ke seluruh Malaysia; seawal 4 jam untuk tempahan terpilih di Lembah Klang (disahkan bertulis). Bermula dari RM799."),
    ('"Ansuran 0%",', '"Ansuran",'),
    ('"value": "1 tahun jaminan penuh (parts dan labor)"', '"value": "1 tahun untuk katil baharu, ikut skop dalam rekod jaminan"'),
    ('"value": "Ansuran 0% sehingga 24 bulan"', '"value": "Ansuran, ditandatangani selepas penghantaran"'),
    ('"value": "Servis percuma sepanjang jaminan"', '"value": "Servis dalam tempoh jaminan ikut rekod jaminan"'),
    (r"re:(<h3[^>]*>(?:<em>)?)Ansuran 0% Faedah((?:</em>)?</h3>)", r"\1Ansuran Tersedia\2"),
    ("Sehingga 24 bulan tanpa faedah", "Ditandatangani selepas penghantaran"),
    (r're:<span style="font-size: 0\.9rem;">Beli ansuran</span> <span style="font-size: 1\.6rem; font-weight: 700;">(?:RM\d+|sebut harga bertulis)</span><span style="font-size: 0\.9rem;">/6bulan</span>',
     '<span style="font-size: 0.9rem;">Ansuran tersedia — ikut sebut harga bertulis</span>'),
    ("Breakeven dalam 10-12 bulan. Selepas itu anda jimat 100% kos sewa bulanan.",
     "Breakeven sekitar 5-6 bulan berbanding sewa. Selepas itu anda tidak lagi membayar sewa bulanan."),
    ("Bayar secara ansuran sehingga 24 bulan tanpa faedah. Serendah RM158/bulan.",
     "Pelan ansuran ditandatangani selepas katil dihantar. Tempoh dan jumlah bulanan dinyatakan dalam sebut harga bertulis."),
    ("Servis Percuma Sepanjang Warranti", "Servis Dalam Tempoh Jaminan"),
    ("Penyelenggaraan dan servis tahunan percuma sepanjang hayat katil.",
     "Servis dalam tempoh jaminan ikut skop rekod jaminan; servis berbayar tersedia selepas itu."),
    ("Aksesori Percuma", "Aksesori Tersedia"),
    ("Tilam, rel sisi, IV pole dan manual pengguna lengkap dalam pakej.",
     "Tilam, IV pole dan aksesori lain dijual berasingan; hanya termasuk jika disenaraikan dalam sebut harga bertulis."),
    (r're:(Dari WhatsApp Ke Rumah Anda — <span[^>]*>)Hanya 4 Jam(</span>)', r"\1Penghantaran Pantas\2"),
    ("Pilih katil yang sesuai. Bayar penuh atau ansuran 0% sehingga 24 bulan.",
     "Pilih katil yang sesuai. Bayar penuh atau secara ansuran — pelan ditandatangani selepas penghantaran."),
    ("Kami hantar dan setup katil di rumah anda dalam masa 3-4 jam.",
     "Kami hantar dan setup katil di rumah anda — seawal 3 jam untuk tempahan terpilih di Lembah Klang, masa sebenar disahkan secara bertulis."),
    ("Dari RM1,300", "Dari RM799"),
    ("PERCUMA + demo penggunaan", "Disediakan + demo penggunaan"),
    (r"re:Harga katil hospital di Malaysia bermula dari (?:<strong>)?RM1,300(?:</strong>)? untuk Katil Hospital 1 Crank, (?:<strong>)?RM1,800(?:</strong>)? untuk Katil Hospital 2 Crank, (?:<strong>)?RM2,500(?:</strong>)? untuk Katil Hospital 3 Crank, dan (?:<strong>)?RM4,500(?:</strong>)? untuk Katil Hospital Elektrik\.",
     "Harga katil hospital kami bermula dari RM799 untuk Katil 2 Fungsi Manual, RM1,349 untuk Katil 3 Fungsi Manual, RM2,799 untuk Katil 3 Fungsi Auto dan RM5,500 untuk Katil Ultra 6 Fungsi Elektrik."),
    (r"re:Ya, kami menawarkan (?:<strong>)?ansuran 0% faedah(?:</strong>)? sehingga 24 bulan\. Contohnya, Katil Hospital 3 Crank boleh dibeli dengan ansuran serendah RM249/bulan selama 10 bulan\.",
     "Ya, pelan ansuran tersedia dan ia ditandatangani selepas katil dihantar — bukan sebelum. Tempoh dan jumlah bulanan dinyatakan dalam sebut harga bertulis."),
    ("Adakah pemasangan percuma ke seluruh Malaysia?", "Adakah pemasangan disediakan ke seluruh Malaysia?"),
    (r"re:Ya, kami menyediakan (?:<strong>)?pemasangan percuma(?:</strong>)? ke seluruh Malaysia\. Untuk kawasan KL dan Selangor, pemasangan boleh dilakukan dalam masa (?:<strong>)?3-4 jam(?:</strong>)? selepas penghantaran\.",
     "Ya, pasukan kami memasang katil di seluruh Malaysia; sebarang caj pemasangan dinyatakan dalam sebut harga bertulis."),
    (r"re:Contohnya, sewa 2 Crank selama 24 bulan = RM5,760, manakala beli = RM1,800\. Anda (<strong>)?jimat lebih RM3,000(</strong>)?",
     r"Contohnya, sewa katil 2 fungsi selama 24 bulan = RM3,600, manakala beli = RM799. Anda \1jimat lebih RM2,800\2"),
    ("✓ Ansuran 0%", "✓ Ansuran Tersedia"),
    ("✓ Servis Percuma Sepanjang Warranti", "✓ Servis Dalam Tempoh Jaminan"),
    ("✓ Pemasangan Percuma", "✓ Pemasangan Disediakan"),
]

# ------------------------------------------------------------ Malay blogs
EXACT["blog/katil-2-fungsi-vs-3-fungsi/index.html"] = [
    ("Katil 3 fungsi: sewa RM200-250/bulan atau beli RM1,299. Perbezaan RM50-100 sebulan.",
     "Katil 3 fungsi: sewa RM250/bulan atau beli RM1,349. Perbezaan RM100 sebulan."),
    ("<td>RM200-250/bulan</td>", "<td>RM250/bulan</td>"),
    ("<td>RM1,299</td>", "<td>RM1,349</td>"),
    ("perbezaan RM50-100/bulan boleh bermakna", "perbezaan RM100/bulan boleh bermakna"),
    (r"re:<td>1 bulan</td>(\s*)<td>RM150</td>(\s*)<td>RM200</td>(\s*)<td>RM50</td>", r"<td>1 bulan</td>\1<td>RM150</td>\2<td>RM250</td>\3<td>RM100</td>"),
    (r"re:<td>3 bulan</td>(\s*)<td>RM450</td>(\s*)<td>RM600</td>(\s*)<td>RM150</td>", r"<td>3 bulan</td>\1<td>RM450</td>\2<td>RM750</td>\3<td>RM300</td>"),
    (r"re:<td>6 bulan</td>(\s*)<td>RM900</td>(\s*)<td>RM1,200</td>(\s*)<td>RM300</td>", r"<td>6 bulan</td>\1<td>RM900</td>\2<td>RM1,500</td>\3<td>RM600</td>"),
    (r"re:<td>12 bulan</td>(\s*)<td>RM1,800</td>(\s*)<td>RM2,400</td>(\s*)<td>RM600</td>", r"<td>12 bulan</td>\1<td>RM1,800</td>\2<td>RM3,000</td>\3<td>RM1,200</td>"),
    ("perbezaan RM50-150 mungkin tidak signifikan", "perbezaan RM100-300 mungkin tidak signifikan"),
]
EXACT["blog/sewa-vs-beli-katil-hospital/index.html"] = [
    ("Untuk katil 3 fungsi, break-even point adalah sekitar 6-7 bulan.", "Untuk katil 3 fungsi (RM1,349 atau RM250/bulan), break-even point adalah sekitar 5-6 bulan."),
    (r"re:<td>1 bulan</td>(\s*)<td>RM200</td>(\s*)(<td rowspan=\"5\"[^>]*>)<strong>RM1,299</strong>", r"<td>1 bulan</td>\1<td>RM250</td>\2\3<strong>RM1,349</strong>"),
    (r"re:<td>3 bulan</td>(\s*)<td>RM600</td>(\s*)<td class=\"highlight-green\">Sewa \(jimat RM699\)</td>", r'<td>3 bulan</td>\1<td>RM750</td>\2<td class="highlight-green">Sewa (jimat RM599)</td>'),
    (r"re:<td>6 bulan</td>(\s*)<td>RM1,200</td>(\s*)<td style=\"color: #F59E0B; font-weight: 600;\">Hampir sama</td>", r'<td>6 bulan</td>\1<td>RM1,500</td>\2<td class="highlight-green">Beli (jimat RM151)</td>'),
    (r"re:<td>9 bulan</td>(\s*)<td>RM1,800</td>(\s*)<td class=\"highlight-green\">Beli \(jimat RM501\)</td>", r'<td>9 bulan</td>\1<td>RM2,250</td>\2<td class="highlight-green">Beli (jimat RM901)</td>'),
    (r"re:<td>12 bulan</td>(\s*)<td>RM2,400</td>(\s*)<td class=\"highlight-green\">Beli \(jimat RM1,101\)</td>", r'<td>12 bulan</td>\1<td>RM3,000</td>\2<td class="highlight-green">Beli (jimat RM1,651)</td>'),
    ("<li>Servis/penyelenggaraan termasuk</li>", "<li>Servis semasa sewa ikut terma sewa bertulis</li>"),
    ("<li>Ansuran 0% tersedia</li>", "<li>Ansuran tersedia (ditandatangani selepas penghantaran)</li>"),
]

# ----------------------------------------------------------- English blog
EXACT["blog/best-hospital-bed-rental-malaysia/index.html"] = [
    ("cheapest hospital bed rental", "affordable hospital bed rental"),
    ("<h3>1. Certification & Safety</h3>", "<h3>1. MDA Registration &amp; Safety</h3>"),
    ("<p><strong>Price Range:</strong> RM150 - RM350/month</p>", "<p><strong>Price Range:</strong> RM150 - RM450/month</p>"),
    ("Prices start from RM150/month for a 2-function manual bed with free setup.", "Prices start from RM150/month for a 2-function manual bed, with no deposit."),
    ("with a 4.9/5 rating from Google reviews. They offer no-deposit rentals, same-day delivery in KL/Selangor, MDA-licensed equipment, 1-year warranty,",
     "with strong Google reviews. They offer no-deposit rentals, delivery from 3 hours for selected KL/Selangor orders (confirmed in writing), MDA-registered beds, a 1-year warranty on new beds,"),
    ("Hospital bed rental in Malaysia costs between RM150-350 per month. A 2-function manual bed costs RM150/month, a 3-function manual bed costs RM200-250/month, and electric beds cost RM300-350/month. Most providers include free setup and maintenance in this price.",
     "At RentHospitalBed.my, hospital bed rental costs RM150-450 per month: RM150/month for a 2-function manual bed, RM250/month for a 3-function manual bed and RM450/month for a 3-function auto bed. The 6-function electric bed is sold (RM5,500), not rented. Setup, delivery and maintenance terms are set out on the written quotation."),
    ("2) 3-Function Manual Beds (RM200-250/month) - adds height adjustment, 3) Electric Beds (RM300-350/month) - motorized controls. All typically include side rails, mattress, and IV pole.",
     "2) 3-Function Manual Beds (RM250/month) - adds height adjustment, 3) 3-Function Auto Beds (RM450/month) - motorized controls. Side rails come with the bed; a mattress, IV pole and other accessories are only included when the written quotation lists them."),
    ("In Kuala Lumpur and Selangor, same-day delivery within 4 hours is available from providers like RentHospitalBed.my. Other states typically receive delivery within 24-48 hours.",
     "In Kuala Lumpur and Selangor, delivery can be as fast as 4 hours for selected orders from providers like RentHospitalBed.my, and from 24 hours in other states — the actual time is confirmed in writing."),
    ("In Kuala Lumpur and Selangor, same-day delivery within 4 hours is available. Other states typically receive delivery within 24-48 hours.",
     "In Kuala Lumpur and Selangor, delivery can be as fast as 4 hours for selected orders, and from 24 hours in other states — the actual time is confirmed in writing."),
    ("Are rental hospital beds in Malaysia medically certified?", "Are rental hospital beds in Malaysia MDA-registered?"),
    ("Reputable providers offer hospital beds certified by KKM (Ministry of Health Malaysia) and registered with MDA (Medical Device Authority). Always verify certification before renting to ensure safety and quality standards.",
     "Reputable providers rent hospital beds registered with MDA (Medical Device Authority). Always ask for the MDA registration number and check that it matches the model before renting."),
    ("Key factors: 1) KKM/MDA certification,", "Key factors: 1) MDA registration that matches the model,"),
    ("4) Included accessories (mattress, side rails, IV pole),", "4) Which accessories (mattress, IV pole) the written quotation lists,"),
    ("with KKM/MDA-licensed equipment, same-day delivery, and no-deposit options.", "with MDA-registered beds, fast delivery and no-deposit options."),
    ("is the top-rated hospital bed rental provider in Malaysia (4.9/5, Google reviews).", "is a hospital bed rental provider in Malaysia with strong Google reviews."),
    ("Same-day delivery available in KL/Selangor. All beds are MDA-licensed with 1-year warranty.",
     "Delivery from 3 hours for selected KL/Selangor orders (confirmed in writing). Beds are MDA-registered; new beds carry a 1-year warranty."),
    (r"re:<td>RM200-250/month</td>(\s*)<td>RM1,299</td>", r"<td>RM250/month</td>\1<td>RM1,349</td>"),
    (r"re:<td><strong>Electric \(6-Function\)</strong></td>(\s*)<td>RM300-350/month</td>(\s*)<td>RM3,500\+</td>",
     r"<td><strong>Electric (6-Function)</strong></td>\1<td>Purchase only</td>\2<td>RM5,500</td>"),
    ("Most reputable providers include free professional setup, mattress, side rails, and IV pole in the rental price. Always confirm what's included before booking.",
     "What a rental includes depends on the provider. At RentHospitalBed.my the monthly price is for the named bed (with side rails); a mattress, IV pole, delivery and setup are only included when the written quotation lists them."),
    ("<li><strong>KKM Approval</strong> - Certified by Malaysia's Ministry of Health</li>", "<li><strong>Model Match</strong> - The MDA record should match the model on your quotation</li>"),
    ("<li><strong>Fast Delivery</strong> - Same-day delivery for urgent needs</li>", "<li><strong>Fast Delivery</strong> - Delivery from 3 hours for selected orders, confirmed in writing</li>"),
    ("<li><strong>Maintenance Support</strong> - Free repairs during rental period</li>", "<li><strong>Maintenance Support</strong> - Repairs during the rental per the written terms</li>"),
    ("<p><strong>Rating:</strong> 4.9/5 (Google reviews)</p>", "<p><strong>Reviews:</strong> Google reviews</p>"),
    ("<li>Same-day delivery in KL/Selangor (within 4 hours)</li>", "<li>Delivery from 3 hours for selected KL/Selangor orders (confirmed in writing)</li>"),
    ("<li>Free maintenance and support</li>", "<li>Maintenance support during rental (per written terms)</li>"),
    ("RM200-250/month rental | RM1,299 to buy", "RM250/month rental | RM1,349 to buy"),
    ("RM300-350/month rental | RM3,500+ to buy", "RM5,500 to buy (not offered for rental)"),
    ("Standard rentals typically include: the hospital bed frame, medical-grade mattress, side rails, IV pole, caster wheels with locks, and free setup.",
     "Our monthly price is for the named hospital bed, including side rails and lockable caster wheels. A mattress, IV pole, delivery and setup are only included when the written quotation lists them."),
    ("<h3>Are the beds certified?</h3>", "<h3>Are the beds MDA-registered?</h3>"),
    ("Reputable providers use KKM (Ministry of Health) approved and MDA (Medical Device Authority) registered equipment. Always ask for certification before renting.",
     "Our hospital beds are registered with MDA (Medical Device Authority), registration GA9817222-107721. Always ask for the registration number before renting."),
    ("Get same-day delivery in KL/Selangor. No deposit required. Free setup and maintenance included.",
     "Delivery from 3 hours for selected KL/Selangor orders (confirmed in writing). No deposit required."),
]
